### ISSUE TITLE
Single qubit simplification rules

### ISSUE THREAD

**Issue by APAChandra** [QuantumSavory/QuantumSymbolics.jl#22]
[Rules_single_qubit.txt](https://github.com/Krastanov/QuantumSavory.jl/files/10763795/Rules_single_qubit.txt)

**Comment by Krastanov** [comment]
@apkille , could you check whether you have implemented these? If so, we can close this issue.

**Comment by apkille** [comment]
I haven't yet, I can make a small PR to implement them.

**Comment by apkille** [comment]
@APAChandra there's several mistakes in the txt file you attached:
- Y*X1 => -iX2, not X2
- H*Y1 => (X1+iX2)/sqrt(2), not X1+iX2
- H*Y2 => (X1-iX2)/sqrt(2), not X1-iX2
