### ISSUE TITLE
`IndentityOp` seems to be destroying some basis information

### ISSUE THREAD

**Issue by Krastanov** [QuantumSavory/QuantumSymbolics.jl#80]
```
julia> express(IdentityOp(X1))
Operator(dim=3x3)
  basis: Fock(cutoff=2)
Eye(3)

julia> express(X1)
Ket(dim=2)
  basis: Spin(1/2)
 0.7071067811865475 + 0.0im
 0.7071067811865475 + 0.0im
```

I would have expected the basis to be the same in both cases, but it seems `IndentityOp` is losing some information and defaulting to a Fock basis even when it should not be a Fock basis.

@apkille , any idea what introduced this? It was detected by the QuantumSavory tests, which regrettably we did not run because we were having a breaking release

**Comment by apkille** [comment]
@krastanov the problem was that the `express_nolookup(x::IdentityOp, r::QuantumOpticsRepr)` converted an `IdentityOp` to an identity operator in the Fock basis in QO.jl (I admit that's my bad). Perhaps a quicker workaround would be defining
```
express_nolookup(x::IdentityOp, r::QuantumOpticsRepr) = isa(x.basis, FockBasis) ? identityoperator(FockBasis(r.cutoff)) : identityoperator(x.basis)
```
